const express = require("express");
const router = express.Router();

//Login autogenerated
const loginController = require("../controllers/auth.controller");
const { forwardAuthenticated } = require("../auth/auth");
//Login page
router.get("/login", forwardAuthenticated, loginController.loginForm);
//Authenticate
router.post("/login", loginController.authenticate);
//Login autogenerated end

//Logout
router.get("/logout", loginController.logout);

module.exports = router;
