exports.mailboxData = [
    {
        id: 1,
        path: 'profile-15.jpeg',
        firstName: 'Laurie',
        lastName: 'Fox',
        email: 'laurieFox@mail.com',
        date: new Date(),
        time: '2:00 PM',
        title: 'Promotion Page',
        displayDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pulvinar feugiat consequat.',
        type: 'inbox',
        isImportant: false,
        isStar: true,
        group: 'social',
        isUnread: false,
        attachments: [
            { name: 'Confirm File.txt', size: '450KB', type: 'file' },
            { name: 'Important Docs.xml', size: '2.1MB', type: 'file' },
        ],
        description: `<p class="mail-content">Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.</p>
        <p>Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.</p>`,
    },
    {
        id: 2,
        path: 'profile-14.jpeg',
        firstName: 'Andy',
        lastName: 'King',
        email: 'kingAndy@mail.com',
        date: new Date(),
        time: '6:28 PM',
        title: 'Hosting Payment Reminder',
        displayDescription: 'Your hosting subscription is due for renewal. Please ensure payment is made before the deadline.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt.</p>
        <p>Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.</p>`,
    },
    {
        id: 3,
        path: '',
        firstName: 'Kristen',
        lastName: 'Beck',
        email: 'kirsten.beck@mail.com',
        date: new Date(),
        time: '11:09 AM',
        title: 'Verification Link',
        displayDescription: 'Please verify your email address by clicking the link below. This link will expire in 24 hours.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: 'social',
        isUnread: true,
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
        <p>Please click the verification button below to verify your email address and complete your registration.</p>`,
    },
    {
        id: 4,
        path: 'profile-16.jpeg',
        firstName: 'Christian',
        lastName: '',
        email: 'christian@mail.com',
        date: '11/30/2025',
        time: '2:00 PM',
        title: 'New Updates',
        displayDescription: 'We have released new updates to improve performance and fix several issues reported by our users.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: 'private',
        isUnread: false,
        attachments: [
            { name: 'update.zip', size: '1.38MB', type: 'zip' },
        ],
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
        <p>Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table.</p>`,
    },
    {
        id: 5,
        path: 'profile-17.jpeg',
        firstName: 'Roxanne',
        lastName: '',
        email: 'roxanne@mail.com',
        date: '11/15/2025',
        time: '2:00 PM',
        title: 'Scheduler Alert',
        displayDescription: 'Your scheduled task is ready for review. Please check the task manager for more details.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: 'personal',
        isUnread: true,
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>`,
    },
    {
        id: 6,
        path: 'profile-18.jpeg',
        firstName: 'Nia',
        lastName: 'Hillyer',
        email: 'niahillyer@mail.com',
        date: '08/16/2025',
        time: '2:22 AM',
        title: 'Motion UI Kit',
        displayDescription: 'Check out the new Motion UI Kit with over 200 pre-built animation components and transitions.',
        type: 'inbox',
        isImportant: true,
        isStar: true,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
        <p>Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table.</p>`,
    },
    {
        id: 7,
        path: 'profile-19.jpeg',
        firstName: 'Iris',
        lastName: 'Hubbard',
        email: 'irishubbard@mail.com',
        date: '08/16/2025',
        time: '1:40 PM',
        title: 'Green Illustration',
        displayDescription: 'New illustration pack available with nature-inspired themes and eco-friendly design elements.',
        type: 'inbox',
        isImportant: true,
        isStar: true,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Brunch 3 wolf moon tempor.</p>`,
    },
    {
        id: 8,
        path: '',
        firstName: 'Ernest',
        lastName: 'Reeves',
        email: 'reevesErnest@mail.com',
        date: '06/02/2025',
        time: '8:25 PM',
        title: 'Youtube Channel Update',
        displayDescription: 'Your YouTube channel analytics report is ready. Views increased by 32% this month.',
        type: 'archive',
        isImportant: true,
        isStar: true,
        group: 'work',
        isUnread: false,
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>`,
    },
    {
        id: 9,
        path: 'profile-20.jpeg',
        firstName: 'Info',
        lastName: 'Company',
        email: 'infocompany@mail.com',
        date: '02/10/2025',
        time: '7:00 PM',
        title: '50% Discount — Limited Time Offer',
        displayDescription: 'Exclusive 50% discount on all premium plans. Offer valid until end of month.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: 'work',
        isUnread: false,
        description: `<p class="mail-content">Take advantage of our exclusive 50% discount offer on all premium business plans.</p>
        <p>This limited-time offer is valid until the end of the month. Don't miss out!</p>`,
    },
    {
        id: 10,
        path: '',
        firstName: 'NPM',
        lastName: 'Inc',
        email: 'npminc@mail.com',
        date: '12/15/2024',
        time: '8:37 AM',
        title: 'npm Inc — Security Advisory',
        displayDescription: 'Important security update regarding npm packages. Several critical vulnerabilities patched.',
        type: 'archive',
        isImportant: false,
        isStar: false,
        group: 'personal',
        isUnread: true,
        attachments: [
            { name: 'package.zip', size: '450KB', type: 'zip' },
        ],
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente.</p>`,
    },
    {
        id: 11,
        path: 'profile-21.jpeg',
        firstName: 'Marlene',
        lastName: 'Wood',
        email: 'marlenewood@mail.com',
        date: '11/25/2024',
        time: '1:51 PM',
        title: 'eBill — Invoice Ready',
        displayDescription: 'Your monthly eBill invoice is ready for download. Total amount: €249.00.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: 'personal',
        isUnread: false,
        description: `<p class="mail-content">Your monthly invoice has been generated and is ready for download.</p>
        <p>Please log in to your account to view and download the invoice. Payment is due within 30 days.</p>`,
    },
    {
        id: 12,
        path: '',
        firstName: 'Keith',
        lastName: 'Foster',
        email: 'kf@mail.com',
        date: '12/15/2024',
        time: '9:30 PM',
        title: 'Web Design News — Weekly Digest',
        displayDescription: 'This week in web design: CSS Grid innovations, new accessibility standards, and top UI trends.',
        type: 'draft',
        isImportant: false,
        isStar: false,
        group: 'personal',
        isUnread: false,
        description: `<p class="mail-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pulvinar feugiat consequat.</p>`,
    },
    {
        id: 13,
        path: '',
        firstName: 'Amy',
        lastName: 'Diaz',
        email: 'amyDiaz@mail.com',
        date: '12/15/2024',
        time: '2:00 PM',
        title: 'Ecommerce Analytics — Q4 Report',
        displayDescription: 'Q4 ecommerce analytics show 45% growth in conversions and 23% increase in average order value.',
        type: 'draft',
        isImportant: false,
        isStar: false,
        group: 'private',
        isUnread: false,
        description: `<p class="mail-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pulvinar feugiat consequat.</p>`,
    },
    {
        id: 14,
        path: '',
        firstName: 'Alan',
        lastName: '',
        email: 'alan@mail.com',
        date: '12/16/2024',
        time: '8:45 AM',
        title: 'Mozilla Update — Firefox 125',
        displayDescription: 'Firefox 125 brings enhanced privacy features, improved performance, and new developer tools.',
        type: 'sent_mail',
        isImportant: false,
        isStar: false,
        group: 'work',
        isUnread: false,
        attachments: [
            { name: 'Confirm File', size: '450KB', type: 'file' },
            { name: 'Important Docs', size: '2.1MB', type: 'folder' },
            { name: 'Photo.png', size: '50kb', type: 'image' },
        ],
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>`,
    },
    {
        id: 15,
        path: '',
        firstName: 'Justin',
        lastName: 'Cross',
        email: 'justincross@mail.com',
        date: '09/14/2024',
        time: '3:10 PM',
        title: 'App Project Checklist',
        displayDescription: 'Here is the updated project checklist. All milestones are on track for the Q1 deadline.',
        type: 'sent_mail',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        attachments: [
            { name: 'Important Docs', size: '2.1MB', type: 'folder' },
            { name: 'Photo.png', size: '50kb', type: 'image' },
        ],
        description: `<p class="mail-content">Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>`,
    },
    {
        id: 16,
        path: 'profile-21.jpeg',
        firstName: 'Alex',
        lastName: 'Gray',
        email: 'alexGray@mail.com',
        date: '08/16/2024',
        time: '10:18 AM',
        title: 'Weekly Newsletter — Design Trends',
        displayDescription: 'This week: Dark mode best practices, glassmorphism updates, and accessible color palettes.',
        type: 'spam',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        attachments: [
            { name: 'Confirm File', size: '450KB', type: 'file' },
            { name: 'Important Docs', size: '2.1MB', type: 'folder' },
            { name: 'Photo.png', size: '50kb', type: 'image' },
        ],
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente.</p>`,
    },
    {
        id: 17,
        path: 'profile-22.jpeg',
        firstName: 'Info',
        lastName: 'Company',
        email: 'infocompany@mail.com',
        date: '02/10/2024',
        time: '7:00 PM',
        title: '50% Discount — Flash Sale',
        displayDescription: 'Flash sale! Get 50% off on all products for the next 48 hours. Shop now!',
        type: 'spam',
        isImportant: false,
        isStar: false,
        group: 'work',
        isUnread: false,
        description: `<p class="mail-content">Don't miss out on our biggest flash sale of the year! 50% off everything!</p>`,
    },
    {
        id: 18,
        path: 'profile-21.jpeg',
        firstName: 'Marlene',
        lastName: 'Wood',
        email: 'marlenewood@mail.com',
        date: '11/25/2024',
        time: '1:51 PM',
        title: 'eBill — Payment Overdue',
        displayDescription: 'Your payment is overdue. Please settle your outstanding balance to avoid service interruption.',
        type: 'spam',
        isImportant: false,
        isStar: false,
        group: 'personal',
        isUnread: false,
        description: `<p class="mail-content">Your payment is overdue. Please settle your outstanding balance.</p>`,
    },
    {
        id: 19,
        path: 'profile-23.jpeg',
        firstName: 'Ryan MC',
        lastName: 'Killop',
        email: 'ryanMCkillop@mail.com',
        date: '08/17/2024',
        time: '11:45 PM',
        title: 'Make it Simple — Design Philosophy',
        displayDescription: 'Simplicity is the ultimate sophistication. Here are 10 principles for cleaner UI design.',
        type: 'trash',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid.</p>`,
    },
    {
        id: 20,
        path: 'profile-23.jpeg',
        firstName: 'Liam',
        lastName: 'Sheldon',
        email: 'liamsheldon@mail.com',
        date: '08/17/2024',
        time: '11:45 PM',
        title: 'New Offers Available',
        displayDescription: 'Check out our latest offers and deals. New products added weekly with exclusive member pricing.',
        type: 'trash',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        attachments: [
            { name: 'Confirm File', size: '450KB', type: 'file' },
        ],
        description: `<p class="mail-content">Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente.</p>`,
    },
    {
        id: 21,
        path: 'profile-21.jpeg',
        firstName: 'Porter',
        lastName: 'Taylor',
        email: 'porter.harber@wiza.info',
        date: '06/01/2025',
        time: '02:40 PM',
        title: 'Project Deadline Reminder',
        displayDescription: 'This is a reminder that the project deadline is approaching. Please submit your deliverables by Friday.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Laudantium enim quasi est quidem magnam voluptate ipsam eos tempora quo necessitatibus dolor quam autem quasi reiciendis et nam sapiente accusantium.</p>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>`,
    },
    {
        id: 22,
        path: 'profile-22.jpeg',
        firstName: 'Brock',
        lastName: 'Mills',
        email: 'brock.gibson@farrell.biz',
        date: '09/08/2025',
        time: '04:20 AM',
        title: 'Quarterly Report — Q3 Results',
        displayDescription: 'Q3 financial results are in. Revenue grew 18% YoY with strong performance across all segments.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Est natus enim nihil est dolore omnis voluptatem numquam et omnis occaecati quod ullam at voluptatem error expedita pariatur.</p>`,
    },
    {
        id: 23,
        path: 'profile-3.jpeg',
        firstName: 'Nyost',
        lastName: 'Terry',
        email: 'nyost@yahoo.com',
        date: '04/01/2025',
        time: '02:10 AM',
        title: 'Team Meeting — Agenda',
        displayDescription: 'Please find the agenda for tomorrow\'s team meeting. Key topics: sprint review, roadmap, hiring.',
        type: 'inbox',
        isImportant: true,
        isStar: false,
        group: 'personal',
        isUnread: false,
        description: `<p class="mail-content">Quia molestiae reprehenderit quasi aspernatur aut expedita occaecati aliquam eveniet laudantium omnis quibusdam delectus saepe.</p>`,
    },
    {
        id: 24,
        path: 'profile-2.jpeg',
        firstName: 'Leonardo',
        lastName: 'Knox',
        email: 'leonardo61@yahoo.com',
        date: '08/08/2024',
        time: '07:50 PM',
        title: 'API Documentation Update',
        displayDescription: 'The API documentation has been updated with new endpoints and authentication flow changes.',
        type: 'inbox',
        isImportant: false,
        isStar: true,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Non et atque occaecati deserunt quas accusantium unde odit nobis qui voluptatem quia voluptas consequuntur itaque dolor.</p>`,
    },
    {
        id: 25,
        path: 'profile-24.jpeg',
        firstName: 'Melisa',
        lastName: 'Mitchell',
        email: 'melisa.legros@mayer.com',
        date: '10/03/2024',
        time: '06:40 AM',
        title: 'Client Feedback — Sprint 12',
        displayDescription: 'Client feedback from Sprint 12 demo is very positive. They highlighted the new dashboard features.',
        type: 'inbox',
        isImportant: true,
        isStar: true,
        group: 'work',
        isUnread: false,
        description: `<p class="mail-content">Harum non quasi et ratione tempore iure ex voluptates in ratione harum architecto fugit inventore cupiditate voluptates magni quo et.</p>`,
    },
    {
        id: 26,
        path: 'profile-26.jpeg',
        firstName: 'Florida',
        lastName: 'Morgan',
        email: 'florida54@gmail.com',
        date: '05/12/2025',
        time: '09:20 PM',
        title: 'Design System — Component Library',
        displayDescription: 'The new component library is ready for review. Includes 45 new components and updated tokens.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Doloribus at sed quis culpa deserunt consectetur qui praesentium accusamus fugiat dicta voluptatem rerum ut voluptate autem.</p>`,
    },
    {
        id: 27,
        path: 'profile-27.jpeg',
        firstName: 'Madison',
        lastName: 'King',
        email: 'madison86@yahoo.com',
        date: '12/04/2024',
        time: '10:40 PM',
        title: 'Infrastructure Migration Plan',
        displayDescription: 'Detailed migration plan for moving from AWS to GCP. Timeline, risks, and rollback procedures included.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: 'private',
        isUnread: false,
        description: `<p class="mail-content">Maiores sed dolores similique labore et inventore et quasi temporibus esse sunt id et eos voluptatem aliquam.</p>`,
    },
    {
        id: 28,
        path: 'profile-30.jpeg',
        firstName: 'Paul',
        lastName: 'Lambert',
        email: 'paul.cruickshank@yahoo.com',
        date: '06/05/2024',
        time: '01:40 AM',
        title: 'Budget Approval — Q2',
        displayDescription: 'Q2 budget has been approved by the board. Total allocation: €1.2M across 5 departments.',
        type: 'inbox',
        isImportant: true,
        isStar: false,
        group: '',
        isUnread: false,
        description: `<p class="mail-content">Ut voluptatem corrupti velit ad voluptatem maiores et nisi velit vero accusamus maiores voluptates quia aliquid ullam eaque.</p>`,
    },
    {
        id: 29,
        path: 'profile-31.jpeg',
        firstName: 'Brakus',
        lastName: 'Morrison',
        email: 'brakus.heidi@gmail.com',
        date: '03/09/2025',
        time: '06:10 PM',
        title: 'Security Audit Results',
        displayDescription: 'Security audit completed. 3 critical issues found and patched. Full report attached.',
        type: 'inbox',
        isImportant: false,
        isStar: true,
        group: 'social',
        isUnread: false,
        description: `<p class="mail-content">Sapiente assumenda molestiae atque adipisci laborum distinctio aperiam et ab ut omnis et occaecati aspernatur odit sit rem expedita.</p>`,
    },
    {
        id: 30,
        path: 'profile-32.jpeg',
        firstName: 'Predovic',
        lastName: 'Peake',
        email: 'predovic.arianna@kirlin.com',
        date: '05/06/2025',
        time: '09:00 AM',
        title: 'Performance Review — Annual',
        displayDescription: 'Annual performance review meeting scheduled for next week. Please prepare your self-assessment.',
        type: 'inbox',
        isImportant: false,
        isStar: false,
        group: 'personal',
        isUnread: false,
        description: `<p class="mail-content">Voluptate iusto quis nobis reprehenderit ipsum amet nulla quia quas dolores velit et non.</p>`,
    },
];
